<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>WordFilterPlus</RootNamespace>
    <AssemblyName>WordFilterPlus</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <OutputPath>$(ElinGamePath)\Package\Mod_WordFilterPlus\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <Deterministic>false</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="package\**" />
    <None Remove="package\**" />
    <EmbeddedResource Remove="package\**" />
  </ItemGroup>
  <Target Name="RemovePdbFromRelease" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <Delete Files="$(OutDir)$(TargetName).pdb" />
  </Target>
  <Target Name="CopyAssets" AfterTargets="AfterBuild">
    <ItemGroup>
      <Assets Include="package\**\*.*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(Assets)"
      DestinationFiles="@(Assets->'$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>
</Project>
